### ISSUE TITLE
custom model

### ISSUE THREAD

**Issue by fahadshery** [statsmaths/cleanNLP#39]
Hi again,

sorry to keep opening these tickets. But i think it is important.

Is there a way we could build and train our own NER model and use it through this package? If not then how could we get it on this package? The built-in models are not suitable for my work area.

Thanks

**Comment by jwijffels** [comment]
You can use the crfsuite R package for this: https://github.com/bnosac/crfsuite

**Comment by fahadshery** [comment]
This is great but struggling to load shinyApp on both windows and Mac

**Comment by taylor-arnold** [comment]
The easiest way to load your own models inside of **cleanNLP** would probably be 
building them in spacy and loading the new spacy model with `cnlp_init_spacy`. Otherwise
as @jwijffels mentions, another package more focused on model building might be more
appropriate if you want to only work within R (and not build the models in Python).
