### ISSUE TITLE
Error thrown when installing cleannlp

### ISSUE THREAD

**Issue by tshjortile** [statsmaths/cleanNLP#69]
Hi! I hope my issue is in the right place here, but since I did not find any solution to this issue so far I was wondering if you could help:
I'm doing a digi hum project using cleannlp with spacy in R, and in my project setup I have run into some issues when installing cleannlp via pip install, which fails to complete due to the following errors:

ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from stanfordnlp->cleannlp) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0.0 (from stanfordnlp->cleannlp)

I installed the latest version of torch (1.3.1) and have python 3.7.

Thank you!
E.

**Comment by taylor-arnold** [comment]
Sorry, just saw this but it was closed. I assume that the issue was resolved? The current problem is that the python package requires both spacy and CoreNLP, even if you only want one (usually not an issue, but I think CoreNLP has some trouble on Windows machines). I need to fix this in the upcoming release.

**Comment by tshjortile** [comment]
Hi! I decided on a different approach as I was not able to solve the
problem I described: In the end it lied with the coreNLP, which was too
difficult to resolve, at least for me. Thank you for getting back to my
request though, I hope to be able to using cleanNLP in the future!

Best wishes

**Comment by taylor-arnold** [comment]
Ah okay, great though sorry that it was such an issue. Can I ask why you
were trying to use CoreNLP rather than one of the other backends? I get
a lot of questions and issues with CoreNLP, but I am not sure why its so
popular in comparison to the UDPipe (super easy to install, lots of langs)
and Spacy (more accurate the CoreNLP, easier to install, fastest
implementation).

**Comment by tshjortile** [comment]
As you probably guessed I am pretty new to text analysis / topic modelling,
and I only mastered R so far in regards to programming languages, so I was
looking for digital humanities tutorials that would give me an overview how
I could approach topic modelling in R using NLP. I found this one, which
includes your CleanNLP - which is the reason I wanted to try it as well:
https://susie-kim.github.io/post/2018-01-09-guide-cnlp-part1/
I realised after a while that I don't need NLP for what I aim to do, and
since I had some problems installing CoreNLP on my windows machine, I
looked for simpler solutions.
I hope this helps in any way!
