### ISSUE TITLE
Improved Documentation

### ISSUE THREAD

**Issue by jamesmartherus** [statsmaths/cleanNLP#72]
Some of the documentation could be more beginner friendly. For example, the output fields of cnlp_annotate() are not explained. What is upos? what is xpos? I'm happy to add to this if you think it would be useful.

**Comment by taylor-arnold** [comment]
Thanks for the feedback. It was well-timed as I was just ready to push a new release today (943e47134eafe3290cebf279ce125cf9b8389ffc and should be on CRAN soon). It is hard to be too specific in the documentation because the exact fields change based on the backend and language being used, but hopefully the new documentation under `cnlp_annotate` is what you are looking for, as well as the (now) properly linked Vignettes.
